title:
description: ""
url: "http://DuaaZahi29.info"
author:
keywords:
github:
medium:
twitter:
email:

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]
include: ["résumé.pdf"]

permalink: pretty
timezone: Asia/Abu_Dhabi

plugins: []

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"

about:
  - name: Github
    username:
    url:
    class: github
  - name: Medium
    username:
    url:
    class: medium
  - name: Twitter
    username:
    url:
    class: twitter
  - name: Email
    username:
    class: email
    url:
